In [120]:
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import numpy as np

In [6]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

## Признаки
№ | Код | Название | Примечание
  ------------- | ------------- | -------------
1 | survival | выжил   | 0 = Нет, 1 = Да
2 | pclass  | Класс билета| 1,2,3
3 | sex	| Пол |	male, female
4|Age| Возраст в годах |
5|sibsp	| Количество братьев, сестер, супруг на борту Титаника |
6|parch | Количество родилетей/детей на борту Титаника |
7|ticket | # билета |
8|fare | Стоимость билета |
9|cabin | № каюты |
10|embarked	| Порт посадки | C = Cherbourg, Q = Queenstown, S = Southampton

In [164]:
train.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [176]:
#X=train[['Sex','Age','SibSp','Parch','Fare']]
X=train[['Sex','Age','SibSp','Parch','Fare']]
X = X.replace(to_replace=['male', 'female'], value=[1, 0])
X['Age']=X['Age'].fillna(X['Age'].mean())
y=train[['Survived']]
scaler = sklearn.preprocessing.StandardScaler()
X=scaler.fit_transform(X)
#X=normalizer.transform(X)
X[0:10]

array([[ 0.73769513, -0.5924806 ,  0.43279337, -0.47367361, -0.50244517],
       [-1.35557354,  0.63878901,  0.43279337, -0.47367361,  0.78684529],
       [-1.35557354, -0.2846632 , -0.4745452 , -0.47367361, -0.48885426],
       [-1.35557354,  0.40792596,  0.43279337, -0.47367361,  0.42073024],
       [ 0.73769513,  0.40792596, -0.4745452 , -0.47367361, -0.48633742],
       [ 0.73769513,  0.        , -0.4745452 , -0.47367361, -0.47811643],
       [ 0.73769513,  1.87005862, -0.4745452 , -0.47367361,  0.39581356],
       [ 0.73769513, -2.13156761,  2.24747049,  0.76762988, -0.22408312],
       [-1.35557354, -0.20770885, -0.4745452 ,  2.00893337, -0.42425614],
       [-1.35557354, -1.20811541,  0.43279337, -0.47367361, -0.0429555 ]])

In [159]:
X

Sex        Age  SibSp  Parch      Fare
0      1  22.000000      1      0    7.2500
1      0  38.000000      1      0   71.2833
2      0  26.000000      0      0    7.9250
3      0  35.000000      1      0   53.1000
4      1  35.000000      0      0    8.0500
5      1  29.699118      0      0    8.4583
6      1  54.000000      0      0   51.8625
7      1   2.000000      3      1   21.0750
8      0  27.000000      0      2   11.1333
9      0  14.000000      1      0   30.0708
10     0   4.000000      1      1   16.7000
11     0  58.000000      0      0   26.5500
12     1  20.000000      0      0    8.0500
13     1  39.000000      1      5   31.2750
14     0  14.000000      0      0    7.8542
15     0  55.000000      0      0   16.0000
16     1   2.000000      4      1   29.1250
17     1  29.699118      0      0   13.0000
18     0  31.000000      1      0   18.0000
19     0  29.699118      0      0    7.2250
20     1  35.000000      0      0   26.0000
21     1  34.000000      0      0   13.0000
22     0  15.000000      0      0    8.0292
23     1  28.000000      0      0   35.5000
24     0   8.000000      3      1   21.0750
25     0  38.000000      1      5   31.3875
26     1  29.699118      0      0    7.2250
27     1  19.000000      3      2  263.0000
28     0  29.699118      0      0    7.8792
29     1  29.699118      0      0    7.8958
..   ...        ...    ...    ...       ...
861    1  21.000000      1      0   11.5000
862    0  48.000000      0      0   25.9292
863    0  29.699118      8      2   69.5500
864    1  24.000000      0      0   13.0000
865    0  42.000000      0      0   13.0000
866    0  27.000000      1      0   13.8583
867    1  31.000000      0      0   50.4958
868    1  29.699118      0      0    9.5000
869    1   4.000000      1      1   11.1333
870    1  26.000000      0      0    7.8958
871    0  47.000000      1      1   52.5542
872    1  33.000000      0      0    5.0000
873    1  47.000000      0      0    9.0000
874    0  28.000000      1      0   24.0000
875    0  15.000000      0      0    7.2250
876    1  20.000000      0      0    9.8458
877    1  19.000000      0      0    7.8958
878    1  29.699118      0      0    7.8958
879    0  56.000000      0      1   83.1583
880    0  25.000000      0      1   26.0000
881    1  33.000000      0      0    7.8958
882    0  22.000000      0      0   10.5167
883    1  28.000000      0      0   10.5000
884    1  25.000000      0      0    7.0500
885    0  39.000000      0      5   29.1250
886    1  27.000000      0      0   13.0000
887    0  19.000000      0      0   30.0000
888    0  29.699118      1      2   23.4500
889    1  26.000000      0      0   30.0000
890    1  32.000000      0      0    7.7500

[891 rows x 5 columns]

Normalizer(copy=True, norm='l2')

In [177]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [188]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit (X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [189]:
reg.score(X_test,y_test)

0.3780330173791131

In [181]:
reg.coef_

array([[-0.25171144, -0.03021007, -0.05117295, -0.03107688,  0.08793134]])

In [182]:
from sklearn import metrics

In [190]:
reg.predict(X_train)

array([[ 0.21010263],
       [ 0.20221853],
       [ 0.13573259],
       [ 0.16253547],
       [ 0.73819429],
       [ 0.64998348],
       [ 0.24123074],
       [ 0.17970725],
       [ 0.20661546],
       [ 0.22087619],
       [ 0.23742741],
       [ 0.19591043],
       [ 0.6406955 ],
       [ 0.15133883],
       [ 0.21104164],
       [ 0.26329974],
       [ 0.69869948],
       [ 0.19931938],
       [ 0.16945765],
       [ 0.15578188],
       [ 0.74048952],
       [ 0.66734036],
       [ 0.69000581],
       [ 0.20528002],
       [ 0.61156518],
       [ 0.23674269],
       [ 0.18367944],
       [ 0.1801189 ],
       [ 0.20880959],
       [ 0.67307042],
       [ 0.73128097],
       [ 0.18333278],
       [ 0.71539705],
       [ 0.61274542],
       [ 0.18849738],
       [ 0.19849238],
       [ 0.13674075],
       [ 0.68408889],
       [ 0.20871684],
       [ 0.16431385],
       [ 0.26211548],
       [ 0.82401565],
       [ 0.67135197],
       [ 0.18243906],
       [ 0.14683257],
       [ 0